In [1]:
import pandas as pd
spot = pd.read_csv('./data/spot/clarkson_data.csv', delimiter=';', parse_dates=['Date'], dayfirst=True)
pmx_forw = pd.read_csv('./data/ffa/PMAX_FFA.csv', delimiter=';', parse_dates=['Date'], dayfirst=True)
csz_forw = pd.read_csv('./data/ffa/CSZ_FFA.csv', delimiter=';', parse_dates=['Date'], dayfirst=True)
smx_forw = pd.read_csv('./data/ffa/SMX_FFA.csv', delimiter=';', parse_dates=['Date'], dayfirst=True)


/var/folders/gh/8c6y7sz92fbdm4xspk2650lm0000gn/T/ipykernel_37974/748165724.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
%pip install scikit-learn
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Merge data frames on the Date column
data_combined = pd.merge(spot, smx_forw, on='Date')
s_col = "SMX"
f_col = "1Q"

# Remove rows with NA or 0 in specific columns (assuming 'SMX' and '1Q' are column names in 'data_combined')
data_combined = data_combined[(data_combined[s_col].notna() & data_combined[s_col] != 0) & (data_combined[f_col].notna() & data_combined[f_col] != 0)]

# Transform data to log levels
data_log_levels = pd.DataFrame()
data_log_levels["spot"] = np.log(data_combined[s_col])
data_log_levels["forwp"] = np.log(data_combined[f_col])
data_log_levels.index = data_combined["Date"]


# Split into train and test sets
split_index = round(len(data_log_levels) * 0.8)
hor = 30
train = data_log_levels.iloc[:split_index]
test = data_log_levels.iloc[split_index:split_index+hor]
#train.head()
data_log_levels.head()
train.head()
#test.head()

# Normalize features
scaler = MinMaxScaler()
train_scal = scaler.fit_transform(train)
print(train_scal)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 4.8 MB/s eta 0:00:0000:010:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.2/301.2 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.3/30.3 MB 8.7 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.
[[0.58835698 0.46232689]
 [0.58560421 0.46323447]
 [0.56566024 0.43324572]
 ...
 [0.39615883 0.29126376]
 [0.40421298 0.28693668]
 [0.40808548 0.2882623 ]]


In [3]:
# Convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=10, is_test=False):
    X, Y = [], []
    if is_test:  # for test data, we just need the last entry for 1-step ahead forecast
        X = dataset[-1:,:,]
        return X, None
    else:
        for i in range(look_back, len(dataset)- hor + 1):
            X.append(dataset[i-look_back:i])
            Y.append(dataset[i:i+hor])
    return np.array(X), np.array(Y)

look_back = 20  # Adjust based on your temporal structure
trainX, trainY = create_dataset(train_scal, look_back)
print(trainX)

[[[0.58835698 0.46232689]
  [0.58560421 0.46323447]
  [0.56566024 0.43324572]
  ...
  [0.58151033 0.40589457]
  [0.58443316 0.41507072]
  [0.59184327 0.43141927]]

 [[0.58560421 0.46323447]
  [0.56566024 0.43324572]
  [0.56119228 0.43027925]
  ...
  [0.58443316 0.41507072]
  [0.59184327 0.43141927]
  [0.59970273 0.44814931]]

 [[0.56566024 0.43324572]
  [0.56119228 0.43027925]
  [0.55692839 0.42903601]
  ...
  [0.59184327 0.43141927]
  [0.59970273 0.44814931]
  [0.60193977 0.43988099]]

 ...

 [[0.20266659 0.24306369]
  [0.19326445 0.25687326]
  [0.19606777 0.2571137 ]
  ...
  [0.27301676 0.10205481]
  [0.23433078 0.21148978]
  [0.22068284 0.2137549 ]]

 [[0.19326445 0.25687326]
  [0.19606777 0.2571137 ]
  [0.20555977 0.26527338]
  ...
  [0.23433078 0.21148978]
  [0.22068284 0.2137549 ]
  [0.20941293 0.20884436]]

 [[0.19606777 0.2571137 ]
  [0.20555977 0.26527338]
  [0.2159535  0.27171733]
  ...
  [0.22068284 0.2137549 ]
  [0.20941293 0.20884436]
  [0.20302236 0.20144473]]]


In [5]:
# Create and fit the MLP model
from keras.layers import Dense
from keras import Sequential
from sklearn.metrics import mean_squared_error
trainX_flat = trainX.reshape(trainX.shape[0], -1)
trainY_flat = trainY.reshape(trainY.shape[0], -1)

model_mlp = Sequential()
model_mlp.add(Dense(32, input_dim=trainX_flat.shape[1], activation='relu'))
model_mlp.add(Dense(trainY_flat.shape[1], activation="linear"))
model_mlp.compile(loss='mean_squared_error', optimizer='adam')
model_mlp.fit(trainX_flat, trainY_flat, epochs=10, batch_size=2, verbose=2)



Epoch 1/10
877/877 - 1s - 918us/step - loss: 0.0154
Epoch 2/10
877/877 - 0s - 495us/step - loss: 0.0077
Epoch 3/10
877/877 - 0s - 514us/step - loss: 0.0072
Epoch 4/10
877/877 - 0s - 500us/step - loss: 0.0069
Epoch 5/10
877/877 - 0s - 448us/step - loss: 0.0067
Epoch 6/10
877/877 - 0s - 456us/step - loss: 0.0064
Epoch 7/10
877/877 - 0s - 457us/step - loss: 0.0064
Epoch 8/10
877/877 - 0s - 459us/step - loss: 0.0064
Epoch 9/10
877/877 - 0s - 450us/step - loss: 0.0062
Epoch 10/10
877/877 - 0s - 438us/step - loss: 0.0060


In [6]:
# Make predictions
trainPredict_scal_flat = model_mlp.predict(trainX_flat)


def create_even_odd_array(arr):
    """
    Returns an array where the first column contains values from even positions
    and the second column contains values from odd positions of the original array.
    """
    return arr.reshape(-1, 2)



testX, _ = create_dataset(trainX, look_back=look_back, is_test=True)
testX_flat = testX.reshape(testX.shape[0], -1)
testPredict_scal_flat = model_mlp.predict(testX_flat)
testPredict_scal = create_even_odd_array(testPredict_scal_flat)


# Invert predictions
#trainPredict = scaler.inverse_transform(trainPredict_scal)
testPredict = scaler.inverse_transform(testPredict_scal)
print(testPredict[:, 0])

# Calculate mean squared error
testScore = mean_squared_error(test["spot"], testPredict[:,0])
testScoreForw = mean_squared_error(test["forwp"], testPredict[:,1])
print('Test Score spot: %.5f MSE' % (testScore))
print('Test Score forw: %.5f MSE' % (testScoreForw))




def random_walk_predictions(training_data, testing_data):
    """
    Generates Random Walk predictions where the next value is assumed to be the last observed value.
    
    Parameters:
    - training_data: DataFrame containing the training data.
    - testing_data: DataFrame containing the test data.
    
    Returns:
    - predictions: Numpy array containing Random Walk predictions for the test set.
    """
    # Last observed values from the training set
    last_observed_spot = training_data['spot'].iloc[-1]
    last_observed_forwp = training_data['forwp'].iloc[-1]
    
    # Create an array of predictions, each one equal to the last observed values
    predictions = np.tile([last_observed_spot, last_observed_forwp], (len(testing_data), 1))
    
    return predictions

# Generate Random Walk predictions for the test set
rw_predictions = random_walk_predictions(train, test)

# Benchmark Random Walk model by calculating the MSE
rw_testScore_spot = mean_squared_error(test["spot"].values, rw_predictions[:, 0])
rw_testScore_forw = mean_squared_error(test["forwp"].values, rw_predictions[:, 1])

print('Random Walk Test Score spot: %.5f MSE' % (rw_testScore_spot))
print('Random Walk Test Score forw: %.5f MSE' % (rw_testScore_forw))

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
[8.567407  8.517986  8.631262  8.551814  8.521142  8.559909  8.531753
 8.675044  8.672477  8.712001  8.725069  8.655896  8.654268  8.75828
 8.646091  8.820569  8.807465  8.7721405 8.753044  8.802827  8.735529
 8.783503  8.739636  8.785037  8.70078   8.697184  8.804268  8.809682
 8.716883  8.778508 ]
Test Score spot: 0.31128 MSE
Test Score forw: 0.13583 MSE
Random Walk Test Score spot: 0.00323 MSE
Random Walk Test Score forw: 0.01074 MSE


In [8]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Define the LSTM model
model_lstm = Sequential()
model_lstm.add(LSTM(units=50, return_sequences=True, input_shape=(trainX.shape[1], trainX.shape[2])))
model_lstm.add(LSTM(units=50))
model_lstm.add(Dense(trainY_flat.shape[1], activation='linear'))  # Assuming multi-step forecasting

model_lstm.compile(loss='mean_squared_error', optimizer='adam')
model_lstm.fit(trainX, trainY_flat, epochs=10, batch_size=32, verbose=2)



Epoch 1/10
55/55 - 2s - 39ms/step - loss: 0.0655
Epoch 2/10
55/55 - 0s - 6ms/step - loss: 0.0106
Epoch 3/10
55/55 - 0s - 6ms/step - loss: 0.0091
Epoch 4/10
55/55 - 0s - 6ms/step - loss: 0.0088
Epoch 5/10
55/55 - 0s - 6ms/step - loss: 0.0087
Epoch 6/10
55/55 - 0s - 6ms/step - loss: 0.0080
Epoch 7/10
55/55 - 0s - 6ms/step - loss: 0.0081
Epoch 8/10
55/55 - 0s - 6ms/step - loss: 0.0074
Epoch 9/10
55/55 - 0s - 6ms/step - loss: 0.0074
Epoch 10/10
55/55 - 0s - 6ms/step - loss: 0.0075


In [9]:
# Prepare the last sequence from the training set as the input for the first prediction
testX_last_sequence = train_scal[-look_back:].reshape(1, look_back, train_scal.shape[1])

# Make predictions
testPredict_scal_flat = model_lstm.predict(testX_last_sequence)

# Since you're predicting `hor` steps ahead, you might need to adjust the code to generate
# multiple steps if your LSTM model is set up for single-step predictions.
# For simplicity, this example directly uses the LSTM output for multi-step predictions.

# Invert scaling
testPredict_scal = create_even_odd_array(testPredict_scal_flat)
testPredict = scaler.inverse_transform(testPredict_scal)


# Calculate and print MSE for each target
testScore_spot_lstm = mean_squared_error(test["spot"].iloc[:hor].values, testPredict[:,0])
testScore_forw_lstm = mean_squared_error(test["forwp"].iloc[:hor].values, testPredict[:,1])
print('LSTM Test Score spot: %.5f MSE' % (testScore_spot_lstm))
print('LSTM Test Score forw: %.5f MSE' % (testScore_forw_lstm))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
LSTM Test Score spot: 0.03600 MSE
LSTM Test Score forw: 0.03061 MSE


In [11]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Number of rounds based on the test set size and forecast horizon
num_rounds =  3  # Adjusted to ensure we don't exceed the test set
look_back = 10  # Adjust based on your temporal structure
hor = 5

# Initialize dictionary to store MSE results for each model
mse_results = {
    'MLP_spot': [],
    'MLP_forwp': [],
    'LSTM_spot': [],
    'LSTM_forwp': [],
    'RW_spot': [],
    'RW_forwp': [],
}


def create_even_odd_array(arr):
    """
    Returns an array where the first column contains values from even positions
    and the second column contains values from odd positions of the original array.
    """
    return arr.reshape(-1, 2)


# Adjust train and test sets for each forecast round
for round in range(1, num_rounds + 1):
    print("Round", round)
    # Define new split point for each round
    split_index = split_index + (round - 1) * hor
    
    # Update train and test sets
    train = data_log_levels.iloc[:split_index]
    test = data_log_levels.iloc[split_index:split_index+hor]

    #Scale train set
    train_scal = scaler.fit_transform(train)

    trainX, trainY = create_dataset(train_scal, look_back)
    # Create and fit the MLP model

    trainX_flat = trainX.reshape(trainX.shape[0], -1)
    trainY_flat = trainY.reshape(trainY.shape[0], -1)

    model_mlp = Sequential()
    model_mlp.add(Dense(32, input_dim=trainX_flat.shape[1], activation='relu'))
    model_mlp.add(Dense(trainY_flat.shape[1], activation="linear"))
    model_mlp.compile(loss='mean_squared_error', optimizer='adam')
    model_mlp.fit(trainX_flat, trainY_flat, epochs=10, batch_size=2, verbose=1)


    # Make predictions
    trainPredict_scal_flat = model_mlp.predict(trainX_flat)
    testX = train_scal[-look_back:].reshape(1, look_back, train_scal.shape[1])
    #testX, _ = create_dataset(trainX, look_back=look_back, is_test=True)
    testX_flat = testX.reshape(testX.shape[0], -1)
    testPredict_scal_flat = model_mlp.predict(testX_flat)
    testPredict_scal = create_even_odd_array(testPredict_scal_flat)

    # Invert predictions
    testPredict_mlp = scaler.inverse_transform(testPredict_scal)

    # Calculate mean squared error
    testScore = mean_squared_error(test["spot"], testPredict_mlp[:,0])
    testScoreForw = mean_squared_error(test["forwp"], testPredict_mlp[:,1])
    print('Test Score spot MLP: %.5f MSE' % (testScore))
    print('Test Score forw MLP: %.5f MSE' % (testScoreForw))



    # Define the LSTM model
    model_lstm = Sequential()
    model_lstm.add(LSTM(units=50, return_sequences=True, input_shape=(trainX.shape[1], trainX.shape[2])))
    model_lstm.add(LSTM(units=50))
    model_lstm.add(Dense(trainY_flat.shape[1], activation='linear'))  # Assuming multi-step forecasting

    model_lstm.compile(loss='mean_squared_error', optimizer='adam')
    model_lstm.fit(trainX, trainY_flat, epochs=10, batch_size=32, verbose=1)

    # Prepare the last sequence from the training set as the input for the first prediction
    #testX_last_sequence = train_scal[-look_back:].reshape(1, look_back, train_scal.shape[1])

    # Make predictions
    testPredict_scal_flat = model_lstm.predict(testX)

    # Since you're predicting `hor` steps ahead, you might need to adjust the code to generate
    # multiple steps if your LSTM model is set up for single-step predictions.
    # For simplicity, this example directly uses the LSTM output for multi-step predictions.

    # Invert scaling
    testPredict_scal = create_even_odd_array(testPredict_scal_flat)
    testPredict_lstm = scaler.inverse_transform(testPredict_scal)


    # Calculate and print MSE for each target
    testScore_spot_lstm = mean_squared_error(test["spot"].iloc[:hor].values, testPredict_lstm[:,0])
    testScore_forw_lstm = mean_squared_error(test["forwp"].iloc[:hor].values, testPredict_lstm[:,1])
    print('LSTM Test Score spot: %.5f MSE' % (testScore_spot_lstm))
    print('LSTM Test Score forw: %.5f MSE' % (testScore_forw_lstm))


    # Random Walk Predictions for comparison
    rw_predictions = random_walk_predictions(train, test)
    
    # Calculate and append MSE for each model for this round
    mse_results['MLP_spot'].append(mean_squared_error(test["spot"], testPredict_mlp[:, 0]))
    mse_results['MLP_forwp'].append(mean_squared_error(test["forwp"], testPredict_mlp[:, 1]))

    mse_results['LSTM_spot'].append(mean_squared_error(test["spot"], testPredict_lstm[:, 0]))
    mse_results['LSTM_forwp'].append(mean_squared_error(test["forwp"], testPredict_lstm[:, 1]))

    mse_results['RW_spot'].append(mean_squared_error(test["spot"], rw_predictions[:, 0]))
    mse_results['RW_forwp'].append(mean_squared_error(test["forwp"], rw_predictions[:, 1]))




Round 1
Epoch 1/10


c:\Users\mariumbo\master-thesis\env\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 489us/step - loss: 0.0494
Epoch 2/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 466us/step - loss: 0.0020
Epoch 3/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 461us/step - loss: 0.0014
Epoch 4/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 461us/step - loss: 0.0014
Epoch 5/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 457us/step - loss: 0.0014
Epoch 6/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 466us/step - loss: 0.0012
Epoch 7/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 449us/step - loss: 0.0013
Epoch 8/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - loss: 0.0013
Epoch 9/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 491us/step - loss: 0.0012
Epoch 10/10
1120/1120 ━━━━━━━━━━━━━━━━━━━━ 1s 490us/step - loss: 0.0011
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


ValueError: Found input variables with inconsistent numbers of samples: [0, 5]

In [ ]:
for key, values in mse_results.items():
    mean = sum(values) / len(values) * 100
    print(f"Mean for {key}: {mean}")